=== jussiarpalahti/odp_tools/src/old_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {},
    "id": "http://example.com/example.json",
    "properties": {
        "author": {
            "id": "/properties/author",
            "type": "string"
        },
        "author_email": {
            "id": "/properties/author_email",
            "type": "string"
        },
        "ckan_url": {
            "id": "/properties/ckan_url",
            "type": "string"
        },
        "extras": {
            "id": "/properties/extras",
            "properties": {
                "agency": {
                    "id": "/properties/extras/properties/agency",
                    "type": "string"
                },
                "categories": {
                    "id": "/properties/extras/properties/categories",
                    "type": "string"
                },
                "date_released": {
                    "id": "/properties/extras/properties/date_released",
                    "type": "string"
                },
                "date_updated": {
                    "id": "/properties/extras/properties/date_updated",
                    "type": "string"
                },
                "external_reference": {
                    "id": "/properties/extras/properties/external_reference",
                    "type": "string"
                },
                "external_reference_en": {
                    "id": "/properties/extras/properties/external_reference_en",
                    "type": "string"
                },
                "external_reference_se": {
                    "id": "/properties/extras/properties/external_reference_se",
                    "type": "string"
                },
                "geographic_coverage": {
                    "id": "/properties/extras/properties/geographic_coverage",
                    "type": "string"
                },
                "geographic_granularity": {
                    "id": "/properties/extras/properties/geographic_granularity",
                    "type": "string"
                },
                "notes_en": {
                    "id": "/properties/extras/properties/notes_en",
                    "type": "string"
                },
                "notes_se": {
                    "id": "/properties/extras/properties/notes_se",
                    "type": "string"
                },
                "source": {
                    "id": "/properties/extras/properties/source",
                    "type": "string"
                },
                "taxonomy_url": {
                    "id": "/properties/extras/properties/taxonomy_url",
                    "type": "string"
                },
                "temporal_coverage-from": {
                    "id": "/properties/extras/properties/temporal_coverage-from",
                    "type": "string"
                },
                "temporal_coverage-to": {
                    "id": "/properties/extras/properties/temporal_coverage-to",
                    "type": "string"
                },
                "temporal_granularity": {
                    "id": "/properties/extras/properties/temporal_granularity",
                    "type": "string"
                },
                "title_en": {
                    "id": "/properties/extras/properties/title_en",
                    "type": "string"
                },
                "title_se": {
                    "id": "/properties/extras/properties/title_se",
                    "type": "string"
                },
                "update_frequency": {
                    "id": "/properties/extras/properties/update_frequency",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "groups": {
            "id": "/properties/groups",
            "items": {
                "id": "/properties/groups/items",
                "type": "string"
            },
            "type": "array"
        },
        "id": {
            "id": "/properties/id",
            "type": "string"
        },
        "isopen": {
            "id": "/properties/isopen",
            "type": "boolean"
        },
        "license": {
            "id": "/properties/license",
            "type": "string"
        },
        "license_id": {
            "id": "/properties/license_id",
            "type": "string"
        },
        "maintainer": {
            "id": "/properties/maintainer",
            "type": "null"
        },
        "maintainer_email": {
            "id": "/properties/maintainer_email",
            "type": "null"
        },
        "metadata_created": {
            "id": "/properties/metadata_created",
            "type": "string"
        },
        "metadata_modified": {
            "id": "/properties/metadata_modified",
            "type": "string"
        },
        "name": {
            "id": "/properties/name",
            "type": "string"
        },
        "notes": {
            "id": "/properties/notes",
            "type": "string"
        },
        "notes_rendered": {
            "id": "/properties/notes_rendered",
            "type": "string"
        },
        "owner_org": {
            "id": "/properties/owner_org",
            "type": "string"
        },
        "private": {
            "id": "/properties/private",
            "type": "boolean"
        },
        "ratings_average": {
            "id": "/properties/ratings_average",
            "type": "null"
        },
        "ratings_count": {
            "id": "/properties/ratings_count",
            "type": "integer"
        },
        "relationships": {
            "id": "/properties/relationships",
            "items": {},
            "type": "array"
        },
        "resources": {
            "id": "/properties/resources",
            "items": {
                "id": "/properties/resources/items",
                "properties": {
                    "cache_last_updated": {
                        "id": "/properties/resources/items/properties/cache_last_updated",
                        "type": "null"
                    },
                    "cache_url": {
                        "id": "/properties/resources/items/properties/cache_url",
                        "type": "null"
                    },
                    "created": {
                        "id": "/properties/resources/items/properties/created",
                        "type": "string"
                    },
                    "description": {
                        "id": "/properties/resources/items/properties/description",
                        "type": "string"
                    },
                    "format": {
                        "id": "/properties/resources/items/properties/format",
                        "type": "string"
                    },
                    "hash": {
                        "id": "/properties/resources/items/properties/hash",
                        "type": "string"
                    },
                    "id": {
                        "id": "/properties/resources/items/properties/id",
                        "type": "string"
                    },
                    "last_modified": {
                        "id": "/properties/resources/items/properties/last_modified",
                        "type": "null"
                    },
                    "mimetype": {
                        "id": "/properties/resources/items/properties/mimetype",
                        "type": "null"
                    },
                    "mimetype_inner": {
                        "id": "/properties/resources/items/properties/mimetype_inner",
                        "type": "null"
                    },
                    "name": {
                        "id": "/properties/resources/items/properties/name",
                        "type": "string"
                    },
                    "package_id": {
                        "id": "/properties/resources/items/properties/package_id",
                        "type": "string"
                    },
                    "position": {
                        "id": "/properties/resources/items/properties/position",
                        "type": "integer"
                    },
                    "resource_group_id": {
                        "id": "/properties/resources/items/properties/resource_group_id",
                        "type": "string"
                    },
                    "resource_type": {
                        "id": "/properties/resources/items/properties/resource_type",
                        "type": "string"
                    },
                    "size": {
                        "id": "/properties/resources/items/properties/size",
                        "type": "null"
                    },
                    "tracking_summary": {
                        "id": "/properties/resources/items/properties/tracking_summary",
                        "properties": {
                            "recent": {
                                "id": "/properties/resources/items/properties/tracking_summary/properties/recent",
                                "type": "integer"
                            },
                            "total": {
                                "id": "/properties/resources/items/properties/tracking_summary/properties/total",
                                "type": "integer"
                            }
                        },
                        "type": "object"
                    },
                    "url": {
                        "id": "/properties/resources/items/properties/url",
                        "type": "string"
                    },
                    "webstore_last_updated": {
                        "id": "/properties/resources/items/properties/webstore_last_updated",
                        "type": "null"
                    },
                    "webstore_url": {
                        "id": "/properties/resources/items/properties/webstore_url",
                        "type": "null"
                    }
                },
                "type": "object"
            },
            "type": "array"
        },
        "revision_id": {
            "id": "/properties/revision_id",
            "type": "string"
        },
        "state": {
            "id": "/properties/state",
            "type": "string"
        },
        "tags": {
            "id": "/properties/tags",
            "items": {
                "id": "/properties/tags/items",
                "type": "string"
            },
            "type": "array"
        },
        "title": {
            "id": "/properties/title",
            "type": "string"
        },
        "tracking_summary": {
            "id": "/properties/tracking_summary",
            "properties": {
                "recent": {
                    "id": "/properties/tracking_summary/properties/recent",
                    "type": "integer"
                },
                "total": {
                    "id": "/properties/tracking_summary/properties/total",
                    "type": "integer"
                }
            },
            "type": "object"
        },
        "type": {
            "id": "/properties/type",
            "type": "string"
        },
        "url": {
            "id": "/properties/url",
            "type": "string"
        },
        "version": {
            "id": "/properties/version",
            "type": "null"
        }
    },
    "type": "object"
}

=== jussiarpalahti/odp_tools/one_package.json
{
            "author": "Vantaan kaupungin perusopetus",
            "author_email": "tilasto@vantaa.fi",
            "ckan_url": "http://ckan.hri.fi/dataset/a2-ja-b2-kielten-opiskelijoiden-maara-vantaalla-kouluittain-luokka-asteittain-ja-kielen-mukaan",
            "extras": {
                "agency": "Vantaan kaupungin sivistystoimi / talous- ja hallintopalvelut",
                "categories": "Opetus ja koulutus",
                "date_released": "03/31/2014",
                "date_updated": "08/09/2016",
                "external_reference": "",
                "external_reference_en": "",
                "external_reference_se": "",
                "geographic_coverage": "Vantaa",
                "geographic_granularity": "Piste",
                "notes_en": "This dataset provides statistics on students learning A2- and B2-languages in Vantaa by school, class and language.",
                "notes_se": "",
                "source": "Vantaan kaupungin sivistysvirasto",
                "taxonomy_url": "",
                "temporal_coverage-from": "2012",
                "temporal_coverage-to": "",
                "temporal_granularity": "vuosi",
                "title_en": "Students learning A2- and B2-languages in Vantaa by school, class and language",
                "title_se": "",
                "update_frequency": "vuosi"
            },
            "groups": [
                "vantaan-sivistystoimen-toimiala-perusopetus"
            ],
            "id": "88d2611c-ae19-480a-8f9d-4b752aa0e27c",
            "isopen": true,
            "license": "Creative Commons Nime\u00e4 4.0 Kansainv\u00e4linen (CC BY 4.0)",
            "license_id": "cc-by-4-fi",
            "maintainer": null,
            "maintainer_email": null,
            "metadata_created": "2014-03-31T11:29:56.375145",
            "metadata_modified": "2016-09-08T05:51:26.711135",
            "name": "a2-ja-b2-kielten-opiskelijoiden-maara-vantaalla-kouluittain-luokka-asteittain-ja-kielen-mukaan",
            "notes": "Vapaaehtoisen A2-kielen opiskelijoiden m\u00e4\u00e4r\u00e4 kouluittain, luokka-asteittain ja kielen mukaan sek\u00e4 valinnaisen B2-kielen opiskelijoiden m\u00e4\u00e4r\u00e4 kouluittain, luokka-asteittain ja kielen mukaan vuodesta 2012 alkaen. Vuodesta 2013 l\u00e4htien tiedoissa on my\u00f6s ruotsin kielikylpyopetukseen ja suomi-saksa kaksikieliseen opetukseen osallistuvien m\u00e4\u00e4r\u00e4t. Tilastointiajankohta on 20.9.\r\n\r\nJokaisen vuoden tilastot ovat Excel-tiedostossa omalla v\u00e4lilehdell\u00e4.",
            "notes_rendered": "<p>Vapaaehtoisen A2-kielen opiskelijoiden m\u00e4\u00e4r\u00e4 kouluittain, luokka-asteittain ja kielen mukaan sek\u00e4 valinnaisen B2-kielen opiskelijoiden m\u00e4\u00e4r\u00e4 kouluittain, luokka-asteittain ja kielen mukaan vuodesta 2012 alkaen. Vuodesta 2013 l\u00e4htien tiedoissa on my\u00f6s ruotsin kielikylpyopetukseen ja suomi-saksa kaksikieliseen opetukseen osallistuvien m\u00e4\u00e4r\u00e4t. Tilastointiajankohta on 20.9.\n</p>\n<p>Jokaisen vuoden tilastot ovat Excel-tiedostossa omalla v\u00e4lilehdell\u00e4.\n</p>",
            "owner_org": "1ec2ce30-f39c-482e-afd6-dba1c28c1a68",
            "private": false,
            "ratings_average": null,
            "ratings_count": 0,
            "relationships": [],
            "resources": [
                {
                    "cache_last_updated": null,
                    "cache_url": null,
                    "created": "2014-03-31T11:34:25.245496",
                    "description": "Excel-tiedosto",
                    "format": "xlsx",
                    "hash": "",
                    "id": "c6a06318-117f-4696-b39e-f99ab4d33298",
                    "last_modified": null,
                    "mimetype": null,
                    "mimetype_inner": null,
                    "name": "",
                    "package_id": "88d2611c-ae19-480a-8f9d-4b752aa0e27c",
                    "position": 0,
                    "resource_group_id": "56a36796-966c-414f-ab76-0b451d391bde",
                    "resource_type": "file",
                    "size": null,
                    "tracking_summary": {
                        "recent": 0,
                        "total": 0
                    },
                    "url": "http://datastore.hri.fi/Vantaa/opetusjakoulutus/A2-_ja_B2-kielet_peruskouluittain_ja_luokka-asteittain_2012-2015.xlsx",
                    "webstore_last_updated": null,
                    "webstore_url": null
                }
            ],
            "revision_id": "3bd9605e-24ac-42c0-8e5c-a5f1cc5a0cd3",
            "state": "active",
            "tags": [
                "kielet",
                "koulutus",
                "opiskelu",
                "peruskoulut"
            ],
            "title": "A2- ja B2-kielten opiskelijoiden m\u00e4\u00e4r\u00e4 Vantaalla kouluittain, luokka-asteittain ja kielen mukaan",
            "tracking_summary": {
                "recent": 0,
                "total": 0
            },
            "type": "dataset",
            "url": "http://www.vantaa.fi/#Varhaiskasvatus ja koulutus",
            "version": null
        }
